sudo: false

language: python

notifications:
  email:
    recipients:
      - "nupic-hackers@lists.numenta.org"
    on_success: change
    on_failure: change
  webhooks: "https://webhooks.gitter.im/e/68f77bae61efa5c931f8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # install gcc-4.8 for C++11 compatibility, #TODO remove when Travis has gcc>=4.8, (it's used for clang too, in coveralls)
      - g++-4.8


env:
  global:
  - NUPIC=$TRAVIS_BUILD_DIR/nupic
  - PYTHONPATH=/home/travis/build/numenta/nupic/lib/python2.7/site-packages:$NUPIC
  - AWS_ACCESS_KEY_ID=AKIAIGHYSEHV3WFKOWNQ
  - secure: BqIdU+D/Vtt5tydjKc1jxc9tHHu8rK9WIv4VysJD++vRSLERYhaSI3Gy1pjB5rrc/VfdLAqWmC7YdmTwEudyVtl0niUF5Zdtztq777qWK2PCxQBUAAXBqaYKNmHDXaBO0I63oTrfevM6OD7UspHqbBzfJhU9RF9GYSy7mz9cvYM=

before_install:

  # Upgrade pip
  - pip install --upgrade pip

  # Wheels is currently used for installation.
  - pip install wheel

  # These are required for the fetch_wheels.py script.
  - pip install requests
  - pip install boto
  - pip install automatatron

  - NUPIC_SHA=`cat nupic_sha.txt`
  - 'echo NUPIC SHA: $NUPIC_SHA'

  # Clone nupic to get the tests & version
  - git clone https://github.com/numenta/nupic.git --depth 50
  - (cd nupic && git reset --hard ${NUPIC_SHA})
  - NUPIC_CORE_VERSION=`python get_nupic_bindings_version.py`

install:

  - echo $PYTHONPATH
  - echo $NUPIC

  # Fetches the binary distribution.
  - python fetch_wheels.py

  # Install wheels we just downloaded.
  - NUPIC_VERSION=`cat ${NUPIC}/VERSION`
  - echo "Installing NuPIC ${NUPIC_VERSION} with wheels..."
  - pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-${NUPIC_CORE_VERSION}-cp27-none-linux_x86_64.whl

  - pip install --use-wheel --find-links=wheelhouse nupic==${NUPIC_VERSION}


script:

  # NuPIC swarming tests
  - cd $NUPIC
  - python ./scripts/run_nupic_tests.py -w

  # NuPIC example runs
  - . ./ci/travis/script-run-examples.sh

  - cd $TRAVIS_BUILD_DIR

  # Regressions tests
  - py.test tests/
